[package]
name = "actix-poc"
version = "0.1.0"
edition = "2021"

include = ["/src"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
serde = { version = "1.0.199", features = ["derive"] }
